config/routes.rb
Rails.application.routes.draw do
  # for landing
  root to: 'landing#index'
  namespace :admin do
    resources :employees, shallow: true do
      collection do
        post :export_csv_file
      end
    end
    resources :contacts
    resources :analyzes
    resources :posts, shallow: true do
      collection do
        post :export_all_posts
        post :export_for_analyze
      end
    end
    resources :teams
    resources :departments
    resources :votes do
      collection do
        post :send_votes
      end
    end
    resources :vote_results, only: [:index, :show, :create], shallow: true do
      collection do
        get :post_vote
      end
    end
  end

  resources :posts, only: :update
  resources :article_comments, only: [:create, :destroy, :update]

  get "bad_request" => "top#bad_request"
  get "internal_server_error" => "top#internal_server_error"
  # Legacy ELB health_check endpoint
  get "health_check" => "top#health_check"

  get	'/price'	    => 'landing#price'
  get	'/privacy'	    => 'landing#privacy'
  get	'/terms'	    => 'landing#terms'
  get	'/integration/slack'	  => 'landing#slack'
  get	'/integration/slack/add'  => 'landing#slack_add'
  get '/contact' => 'landing#contact'
  post '/contact/complete' => 'landing#contact_mail'

  # login
  get	'/login'		      => 'users#login'
  post	'/login/complete'	      => 'users#login_complete'
  get	'/logout'		      => 'users#logout'
  get	'/company/login'	      => 'company#login'

  # registration
  get	'/company/register'	      => 'company#create'
  post	'/company/register/complete'  => 'company#create_complete'
  get	'/update'		      => 'users#update'
  post	'/update/complete'	      => 'users#update_complete', :as => 'user'
  get	'/invite'		      => 'users#invite'
  post	'/invite/complete'	      => 'users#invite_complete'

  # company
  # get	'/company'			    => 'company#index'
  get	'/company/details'		    => 'company#details'
  get	'/company/edit'			    => 'company#edit'
  post	'/company/edit/complete'	    => 'company#edit_complete'
  get '/company/customize' => 'company#customize'
  post '/company/customize/update' => 'company#customize_update'
  get	'/company/employees'		    => 'company#employees'
  post '/company/employees' => 'company#employees'
  post  '/company/employees/edit/complete'  => 'company#edit_employees_complete'
  post  '/company/employees/delete'     => 'company#delete_employees'
  get '/company/employees/register' => 'company#register_employees'
  post '/company/employees/create_users_by_csv'      => 'company#create_users_by_csv'
  post '/company/employees/create_department_and_team_by_csv' => 'company#create_department_and_team_by_csv'
  post '/company/employees/export_csv_format_create_user' => 'company#export_csv_format_create_user'
  post '/company/employees/export_csv_format_create_department_and_team' => 'company#export_csv_format_create_department_and_team'
  post 'company/employees/register/complete' => 'company#register_employees_complete'
  get	'/company/employees/add'	    => 'company#add_employees'
  post	'/company/employees/add/complete'   => 'company#add_employees_complete'
  get	'/company/employees/edit/:user_id'  => 'company#edit_employees'
  get	'/company/rewards'		    => 'company#rewards'
  get	'/company/rewards/add'		    => 'company#add_rewards'
  post	'/company/rewards/add/complete'	    => 'company#add_rewards_complete'
  get	'/company/rewards/edit/:reward_id'  => 'company#edit_rewards'
  post	'/company/rewards/edit/complete'    => 'company#edit_rewards_complete'
  post	'/company/rewards/delete'	    => 'company#delete_rewards'
  # get	'/company/rewards/request'	    => 'company#rewards_request'
  # post	'/company/rewards/request/action'   => 'company#rewards_request_action'
  # get	'/company/bonus'		    => 'company#bonus'
  # get	'/company/bonus/add'		    => 'company#add_bonus'
  # post	'/company/bonus/add/complete'	    => 'company#add_bonus_complete'
  # get	'/company/bonus/edit/:bonus_id'     => 'company#edit_bonus'
  # post	'/company/bonus/edit/complete'	    => 'company#edit_bonus_complete'
  # post	'/company/bonus/delete'		    => 'company#delete_bonus'
  post	'/company/employees/make_admin'	    => 'company#make_admin'
  post	'/company/employees/make_user'	    => 'company#make_user'
  post	'/company/employees/make_manager'   => 'company#make_manager'
  post	'/company/employees/make_non_manager' => 'company#make_non_manager'
  get '/company/employees/edit_email' => 'company#edit_email'
  post '/company/employees/update' => 'company#update_email'
  # get	'/company/teams'		    => 'company#teams'
  # post	'/company/teams/add/complete'	    => 'company#add_teams_complete'
  # get	'/company/teams/edit/:team_id'	    => 'company#edit_teams'
  # post	'/company/teams/edit/:team_id/complete'	    => 'company#edit_teams_complete'
  # post	'/company/teams/delete'		    => 'company#delete_teams'
  # get '/company/team/:id/show'        => 'company#team_show'
  # post	'/company/departments/add/complete'	    => 'company#add_departments_complete'
  # get	'/company/departments/edit' => 'company#edit_departments'
  # post	'/company/departments/edit/complete'	=> 'company#edit_departments_complete'
  # post	'/company/departments/delete'	    => 'company#delete_departments'
  post '/company/confirm_invite_email_setting' => 'company#confirm_invite_email_setting'
 
  # users
  get	'/user'			    => 'users#index'
  get '/user/getname' => 'users#give_recog_by_email'
  post	'/user/give_points'	    => 'users#give_points'
  post	'/user/give_points_slack'   => 'users#give_points_slack'
  #post	'/user/give_comments'	    => 'users#give_comments'
  #post	'/user/give_kudos'	    => 'users#give_kudos'
  post	'/user/give_bonus'	    => 'users#give_bonus'
  post	'/user/delete_post'	    => 'users#delete_post'
  #post	'/user/delete_comment'	    => 'users#delete_comment'

  get	'/profile'		            => 'users#profile'
  get '/profile/given'          => 'users#given'
  get '/profile/timeline'       => 'users#timeline'
  get '/profile/articles'       => 'users#articles'
  post '/profile/give_kudos'    => 'users#give_kudos'
  post '/profile/give_comments' => 'users#give_comments'
  post '/profile/delete_comment' => 'users#delete_comment'

  # get	'/rewards'		    => 'users#rewards'
  # post	'/rewards/request'	    => 'users#rewards_request'
  # get	'/rewards/status'	    => 'users#rewards_status'
  # post	'/rewards/cancel'	    => 'users#rewards_cancel'
  # get	'/bonus'		    => 'users#bonus'
  post '/select_target_department' => 'users#select_target_department'
  post '/select_target_team' => 'users#select_target_team'

  #analytics
  get	'analytics'		=> 'analytics#overall'
  post	'analytics'		=> 'analytics#overall'
  get	'analytics/receiver'	=> 'analytics#index'
  post	'analytics/receiver'	=> 'analytics#index'
  get	'analytics/giver'	=> 'analytics#giver'
  post	'analytics/giver'	=> 'analytics#giver'
  get	'analytics/hashtag'	=> 'analytics#hashtag'
  post	'analytics/hashtag'	=> 'analytics#hashtag'
  get 'analytics/hashtag/points' => 'analytics#hashtagpoints'
  post 'analytics/hashtag/points' => 'analytics#hashtagpoints'
  get	'analytics/hashtag/all' => 'analytics#allhashtag'
  post	'analytics/hashtag/all' => 'analytics#allhashtag'
  get 'analytics/hashtag/all/points' => 'analytics#allhashtagpoints'
  post  'analytics/hashtag/all/points' => 'analytics#allhashtagpoints'
  get 'analytics/users' => 'analytics#users'
  post 'analytics/users' => 'analytics#users'
  get	'analytics/user/:id'	=> 'analytics#user'
  post	'analytics/user/:id'	=> 'analytics#user'
  get 'analytics/user/:id/points'  => 'analytics#userpoints'
  post  'analytics/user/:id/points'  => 'analytics#userpoints'
  get 'analytics/user/:id/given' => 'analytics#usergiven'
  get 'analytics/user/:id/given' => 'analytics#usergiven'
  get 'analytics/user/:id/received' => 'analytics#userreceived'
  get  'analytics/teams'    => 'analytics#teams'
  get 'analytics/pv'  => 'analytics#pv'
  post 'analytics/pv'  => 'analytics#pv'
  #get 'analytics/callback'  => 'analytics#callback'

  post 'tracking/pv' => 'tracking#track_pv'

  # blog
  get '/company/articles' => 'articles#index'
  get '/company/casual_articles' => 'articles#casual'
  get '/company/article/new' => 'articles#new'
  get '/company/article/:id' => 'articles#show'
  post '/company/article/create'  => 'articles#create'
  get '/company/article/:id/edit' => 'articles#edit'
  post '/company/article/:id/update'  => 'articles#update'
  post '/company/article/:id/destory'     => 'articles#destory'
  post '/company/article/:id/publish' => 'articles#publish'
  post '/company/article/send_release_mail' => 'articles#send_release_mail'
  post '/company/article/:id/update_is_new' => 'articles#update_is_new'
  post '/company/article/like' => 'articles#like'
  get '/company/image/:id/edit' => 'articles#image'
  post '/company/image/:id/update' => 'articles#image_update'
  post '/company/image/:id/delete' => 'articles#image_delete'
  get '/company/tags' => 'tags#index'
  get '/company/user_posted_contents' => 'user_posted_contents#index'
  post '/company/user_posted_content/create'  => 'user_posted_contents#create'  

  # banner
  get '/company/banners' => 'banners#index'
  post '/company/banner/create'  => 'banners#create'

  #facebook auth
  get	'auth/facebook', as: "auth_provider"
  get	'auth/facebook/callback',to: "users#fb_auth"

  #forget password
  get	'/forgot_password'		  => 'users#forgot_password'
  post	'/forgot_password/submit'	  => 'users#forgot_password_submit'

  #ios register
  post	'/device/ios/register'		  => 'device#register_ios'
  post	'/device/ios/unregister'	  => 'device#unregister_ios'

  match "*anything" => "top#not_found" , via: [:get, :post , :patch , :delete ]
end

app/models/article.rb
class Article < ActiveRecord::Base
  is_impressionable

	belongs_to :category
	has_many :titles
	has_many :texts
	has_many :links
	has_many :quotations
	has_many :tags
  has_many :users, through: :tags
  has_many :article_likes
  has_many :users, through: :article_likes
  has_many :images
  has_many :article_comments

  validates :title, length: {maximum: 250}
  validates :description, length: {maximum: 250}

  scope :available, -> { where(is_deleted: 0) }
  scope :of_company, ->(company_id) { where(company_id: company_id) }
end

app/views/articles/casual.html.erb
<div id="admin_wrapper">
  <%= render "/company/admin_subheader" %>

	<div id="admin_contents" class="c_align">
	  <h3>ブログ</h3>
	  <div class="margin-10">
	    <%= link_to "+ 記事を作成する", company_article_new_path, {class: "a_btncmn radius5 width-250"} %>
      <%= link_to "+ ニュース記事一覧", company_articles_path, {class: "a_btncmn radius5 width-250"} %>
	    <%= link_to "+ 社員からの投稿を見る", company_user_posted_contents_path, {class: "a_btncmn radius5 width-250"} %>
	  </div>

	  <% if @articles.count == 0 %>
	    <h3>カジュアル記事が作成されていません</h3>
	  <% else %>
	  	  <% if flash[:notice] %><p class="c_align notice" style="color: red;"><b><i><%= raw flash[:notice] %></i></b></p><br><% end %>
		  <h3 class="margin-bottom-10">作成したカジュアル記事一覧</h3>
		  <p>現在の公開記事数: <%= @articles.where(is_published: 1).count %>記事</p>
		  <div style="margin: 10px auto 0px;">
		    <div >
			  <table class="admin_table c_align width-90-percent">
			  	<tr>
			  	  <th scope="row width-8-percent">作成日</th>
			  	  <th scope="row width-30-percent">タイトル</th>
			  	  <th scope="row width-8-percent">いいね数</th>
			  	  <th scope="row width-8-percent">PV数</th>
			  	  <th scope="row width-8-percent">公開/未公開</th>
			  	  <th scope="row width-8-percent">編集</th>
			  	  <th scope="row width-8-percent">削除</th>
			  	  <th scope="row width-8-percent">メール送信</th>
			  	</tr>
			  	<% @articles.each do |article| %>
				  	<tr>
				  	  <td class="width-8-percent"><%= article.updated_at.strftime("%Y/%m/%d") %></td>
				  	  <td class="width-30-percent"><%= link_to article.title.truncate(35), "/company/article/#{article.id}" %></td>
				  	  <td class="width-8-percent"><%= article.article_likes.count %></td>
				  	  <td class="width-8-percent"><%= number_with_delimiter(article.impressionist_count) %></td>
				  	  <td class="width-8-percent">
				  	    <% if article.is_published == 0 %>
				  	    	<%= link_to "未公開", "/company/article/#{article.id}/publish",{method: :post, title: "公開する", data: { :confirm => "選択した記事を公開しますか？"}} %>
				  	    <% else %>
				  	      <%= link_to "公開済み", "/company/article/#{article.id}/publish", {method: :post, title: "非公開にする", data: { :confirm => "選択した記事を非公開にしますか？"}} %>
				  	    <% end %>
				  	  </td>
				  	  <td class="width-8-percent"><%= link_to "編集", "/company/article/#{article.id}/edit" %></td>
				  	  <td class="width-8-percent"><%= link_to "削除", "/company/article/#{article.id}/destory", method: :post %></td>
				  	  <td class="width-8-percent show-modal" id=<%= Rails.root.to_s + "/company/article/#{article.id}" %> value=<%= "#{article.title}" %>><%= link_to "メール送信", "#{article.id}" %></td>
				  	</tr>
			  	<% end %>
			  </table>
			</div>
	  <% end %>
	</div>
</div>

<div id="modalwin" class="modalwin hide">
  <a herf="#" class="modal-close"></a>
  <h1>メール送信</h1>
  <div class="modalwin-contents">
    <%= form_tag( "", method: "get", id: "login_form" ) do %>
	    <div class="description">
	      <p>件名<br/>
	        <input autofocus="autofocus" type="text" name="title" required size="50" placeholder="メッセージを入力してください" style="font-size: 14px; padding: 8px;border:1px gray solid;">
	      </p>
	      <p>内容<br/>
	        <textarea name="message" id="description" required rows="15" cols="75" style="font-size: 14px; padding: 8px;" placeholder="メッセージを入力してください"></textarea>
	      </p>
	    </div>
      <p align="right"><input type="submit" value="送信する"/></p>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $(function () {
    // モーダルウィンドウを開く
    function showModal(event) {
      event.preventDefault();
      var $shade = $('<div></div>');
      $shade
        .attr('id', 'shade')
        .on('click', hideModal);
      var $modalWin = $('#modalwin');
      var $window = $(window);
      var posX = ($window.width() - $modalWin.outerWidth()) / 2;
      var posY = ($window.height() - $modalWin.outerHeight()) / 2;
      $modalWin
        .before($shade)
        .css({left: posX, top: posY})
        .removeClass('hide')
        .addClass('show')
        .on('click', 'button', function () {
          hideModal();
        });
      }
      function hideModal() {
        $('#shade').remove();
        $('#modalwin')
        .removeClass('show')
        .addClass('hide');
      }

      $('.show-modal').on('click', showModal);

			$('.show-modal').on('click', function(){
			    var url =  $(this).attr("id");
			    var title = $(this).attr("value")
          // $(".description textarea").attr("placeholder",id);
          $(".description textarea").val("新しい記事が公開されました！" + "\n" + "\n"  + title + "\n" + url);
			});
      // title.setAttribute("placeholder", "リンクタイトル");


    }());
</script>

app/views/articles/image.html.erb
<div id="admin_wrapper">
  <%= render "/company/admin_subheader" %>

  <div id="admin_contents" class="c_align">
    <h3>ブログ</h3>
    <div class="margin-10">
      <%= link_to "+ 記事を作成する", company_article_new_path, {class: "a_btncmn radius5 width-250"} %>
      <%= link_to "+ ニュース記事一覧", company_articles_path, {class: "a_btncmn radius5 width-250"} %>
      <%= link_to "+ カジュアル記事一覧", company_casual_articles_path, {class: "a_btncmn radius5 width-250"} %>
      <%= link_to "+ 社員からの投稿を見る", company_user_posted_contents_path, {class: "a_btncmn radius5 width-250"} %>
    </div>

    <div class="margin-top-10">
      <h3 class="margin-bottom-10">画像を更新する</h3>
      <h4 class="margin-10"><%= link_to "記事に戻る", "/company/article/#{@image.article_id}/edit", style: "text-decoration: none;" %></h4>
      <%= form_tag( "/company/image/#{@image.id}/update", :multipart => true, method: "post") do %>
        <table class="article_table horizontal width-80-percent">
          <tr>
            <th class="width-20-percent">現在の画像</th>
            <td class="width-80-percent">
              <%= image_tag @image.img_src, class: "height-300" %>
            </td>
          </tr>
          <tr>
            <th class="width-20-percent">画像</th>
            <td class="width-80-percent"><input name="img_src" type="file"></td>
          </tr>
          <tr>
            <th class="width-20-percent">削除</th>
            <td class="width-80-percent"><%= link_to "削除する", "/company/image/#{@image.id}/delete", method: :post %></td>
          </tr>
        </table>
        <input class="c_align margin-10" type="submit" value="送信" id="submit-btn"/>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div id="admin_wrapper">
  <%= render "/company/admin_subheader" %>
	<div id="admin_contents" class="c_align">
	  <h3>ブログ</h3>
	  <div class="margin-10">
	    <%= link_to "+ 記事を作成する", company_article_new_path, {class: "a_btncmn radius5 width-250"} %>
	    <%= link_to "+ カジュアル記事一覧", company_casual_articles_path, {class: "a_btncmn radius5 width-250"} %>
	    <%= link_to "+ 社員からの投稿を見る", company_user_posted_contents_path, {class: "a_btncmn radius5 width-250"} %>
	  </div>
	  <% if @articles.count == 0 %>
	    <h3>ニュース記事が作成されていません</h3>
	  <% else %>
      <% if flash[:notice] %><p class="c_align notice" style="color: red;"><b><i><%= raw flash[:notice] %></i></b></p><br><% end %>
		  <h3 class="margin-bottom-10">作成したニュース記事一覧</h3>
		  <p>現在の公開記事数: <%= @articles.where(is_published: 1).count %>記事</p>
		  <div style="margin: 10px auto 0px; padding-bottom: 30px;">
		    <div >
			  <table class="admin_table c_align width-90-percent">
			  	<tr>
			  	  <th scope="row width-8-percent">作成日</th>
			  	  <th scope="row width-30-percent">タイトル</th>
			  	  <th scope="row width-8-percent">いいね数</th>
			  	  <th scope="row width-8-percent">コメント数</th>
			  	  <th scope="row width-8-percent">PV数</th>
			  	  <th scope="row width-8-percent">公開/未公開</th>
			  	  <th scope="row width-8-percent">Newバッチ</th>
			  	  <th scope="row width-8-percent">編集</th>
			  	  <th scope="row width-8-percent">削除</th>
			  	  <th scope="row width-8-percent">メール送信</th>
			  	</tr>
			  	<% @articles.each do |article| %>
				  	<tr>
				  	  <td class="width-8-percent"><%= article.updated_at.strftime("%Y/%m/%d") %></td>
				  	  <td class="width-20-percent"><%= link_to article.title.truncate(35), "/company/article/#{article.id}" %></td>
				  	  <td class="width-8-percent"><%= article.article_likes.count %></td>
				  	  <td class="width-8-percent"><%= article.article_comments.available.count %></td>
				  	  <td class="width-8-percent"><%= number_with_delimiter(article.impressionist_count) %></td>
				  	  <td class="width-8-percent">
				  	    <% if article.is_published == 0 %>
				  	    	<%= link_to "未公開", "/company/article/#{article.id}/publish",{method: :post, title: "公開する", data: { :confirm => "選択した記事を公開しますか？"}} %>
				  	    <% else %>
				  	      <%= link_to "公開済み", "/company/article/#{article.id}/publish", {method: :post, title: "非公開にする", data: { :confirm => "選択した記事を非公開にしますか？"}} %>
				  	    <% end %>
				  	  </td>
				  	  <td class="width-8-percent">
				  	    <% if article.is_new == 1 %>
				  	    	<%= link_to "New", "/company/article/#{article.id}/update_is_new",{method: :post, title: "バッチを外す", data: { :confirm => "選択した記事から「New」バッチを外しますか？"}} %>
				  	    <% else %>
				  	      <%= link_to "-", "/company/article/#{article.id}/update_is_new", {method: :post, title: "バッチをつける", data: { :confirm => "選択した記事に「New」バッチをつけますか？"}} %>
				  	    <% end %>
				  	  </td>
				  	  <td class="width-8-percent"><%= link_to "編集", "/company/article/#{article.id}/edit" %></td>
				  	  <td class="width-8-percent"><%= link_to "削除", "/company/article/#{article.id}/destory", method: :post, data: {confirm: "選択した記事「#{article.title}」を削除しますか?"} %></td>
				  	  <td class="width-8-percent show-modal" id=<%= "https://www.prizy.me/company/article/#{article.id}" %> value=<%= "#{article.title}" %>><%= link_to "メール送信", "#{article.id}" %></td>
				  	</tr>
			  	<% end %>
			  </table>
			</div>
	  <% end %>
	</div>
</div>

<div id="modalwin" class="modalwin hide">
  <a herf="#" class="modal-close"></a>
  <h1>メール送信</h1>
  <div class="modalwin-contents">
    <%= form_tag( "/company/article/send_release_mail", method: "post", id: "login_form" ) do %>
	    <div class="description">
	      <p>件名<br/>
	        <input autofocus="autofocus" type="text" name="subject" required size="50" placeholder="メッセージを入力してください" style="font-size: 14px; padding: 8px;border:1px gray solid;">
	      </p>
	      <p>内容<br/>
	        <textarea name="description" id="description" required rows="15" cols="75" style="font-size: 14px; padding: 8px;" placeholder="メッセージを入力してください"></textarea>
	      </p>
	    </div>
      <p align="right"><input type="submit" value="送信する"/></p>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $(function () {
    // モーダルウィンドウを開く
    function showModal(event) {
      event.preventDefault();
      var $shade = $('<div></div>');
      $shade
        .attr('id', 'shade')
        .on('click', hideModal);
      var $modalWin = $('#modalwin');
      var $window = $(window);
      var posX = ($window.width() - $modalWin.outerWidth()) / 2;
      var posY = ($window.height() - $modalWin.outerHeight()) / 2;
      $modalWin
        .before($shade)
        .css({left: posX, top: posY})
        .removeClass('hide')
        .addClass('show')
        .on('click', 'button', function () {
          hideModal();
        });
      }
      function hideModal() {
        $('#shade').remove();
        $('#modalwin')
        .removeClass('show')
        .addClass('hide');
      }

      $('.show-modal').on('click', showModal);

			$('.show-modal').on('click', function(){
			    var url =  $(this).attr("id");
			    var title = $(this).attr("value")
          // $(".description textarea").attr("placeholder",id);
          $(".description textarea").val("新しい記事が公開されました！" + "\n" + "\n"  + title + "\n" + url);
			});
      // title.setAttribute("placeholder", "リンクタイトル");
    }());
</script>