config/routes.rb
Rails.application.routes.draw do
  # for landing
  root to: 'landing#index'
  namespace :admin do
    resources :employees, shallow: true do
      collection do
        post :export_csv_file
      end
    end
    resources :contacts
    resources :analyzes
    resources :posts, shallow: true do
      collection do
        post :export_all_posts
        post :export_for_analyze
      end
    end
    resources :teams
    resources :departments
    resources :votes do
      collection do
        post :send_votes
      end
    end
    resources :vote_results, only: [:index, :show, :create], shallow: true do
      collection do
        get :post_vote
      end
    end
  end

  resources :posts, only: :update
  resources :article_comments, only: [:create, :destroy, :update]

  get "bad_request" => "top#bad_request"
  get "internal_server_error" => "top#internal_server_error"
  # Legacy ELB health_check endpoint
  get "health_check" => "top#health_check"

  get	'/price'	    => 'landing#price'
  get	'/privacy'	    => 'landing#privacy'
  get	'/terms'	    => 'landing#terms'
  get	'/integration/slack'	  => 'landing#slack'
  get	'/integration/slack/add'  => 'landing#slack_add'
  get '/contact' => 'landing#contact'
  post '/contact/complete' => 'landing#contact_mail'

  # login
  get	'/login'		      => 'users#login'
  post	'/login/complete'	      => 'users#login_complete'
  get	'/logout'		      => 'users#logout'
  get	'/company/login'	      => 'company#login'

  # registration
  get	'/company/register'	      => 'company#create'
  post	'/company/register/complete'  => 'company#create_complete'
  get	'/update'		      => 'users#update'
  post	'/update/complete'	      => 'users#update_complete', :as => 'user'
  get	'/invite'		      => 'users#invite'
  post	'/invite/complete'	      => 'users#invite_complete'

  # company
  # get	'/company'			    => 'company#index'
  get	'/company/details'		    => 'company#details'
  get	'/company/edit'			    => 'company#edit'
  post	'/company/edit/complete'	    => 'company#edit_complete'
  get '/company/customize' => 'company#customize'
  post '/company/customize/update' => 'company#customize_update'
  get	'/company/employees'		    => 'company#employees'
  post '/company/employees' => 'company#employees'
  post  '/company/employees/edit/complete'  => 'company#edit_employees_complete'
  post  '/company/employees/delete'     => 'company#delete_employees'
  get '/company/employees/register' => 'company#register_employees'
  post '/company/employees/create_users_by_csv'      => 'company#create_users_by_csv'
  post '/company/employees/create_department_and_team_by_csv' => 'company#create_department_and_team_by_csv'
  post '/company/employees/export_csv_format_create_user' => 'company#export_csv_format_create_user'
  post '/company/employees/export_csv_format_create_department_and_team' => 'company#export_csv_format_create_department_and_team'
  post 'company/employees/register/complete' => 'company#register_employees_complete'
  get	'/company/employees/add'	    => 'company#add_employees'
  post	'/company/employees/add/complete'   => 'company#add_employees_complete'
  get	'/company/employees/edit/:user_id'  => 'company#edit_employees'
  get	'/company/rewards'		    => 'company#rewards'
  get	'/company/rewards/add'		    => 'company#add_rewards'
  post	'/company/rewards/add/complete'	    => 'company#add_rewards_complete'
  get	'/company/rewards/edit/:reward_id'  => 'company#edit_rewards'
  post	'/company/rewards/edit/complete'    => 'company#edit_rewards_complete'
  post	'/company/rewards/delete'	    => 'company#delete_rewards'
  # get	'/company/rewards/request'	    => 'company#rewards_request'
  # post	'/company/rewards/request/action'   => 'company#rewards_request_action'
  # get	'/company/bonus'		    => 'company#bonus'
  # get	'/company/bonus/add'		    => 'company#add_bonus'
  # post	'/company/bonus/add/complete'	    => 'company#add_bonus_complete'
  # get	'/company/bonus/edit/:bonus_id'     => 'company#edit_bonus'
  # post	'/company/bonus/edit/complete'	    => 'company#edit_bonus_complete'
  # post	'/company/bonus/delete'		    => 'company#delete_bonus'
  post	'/company/employees/make_admin'	    => 'company#make_admin'
  post	'/company/employees/make_user'	    => 'company#make_user'
  post	'/company/employees/make_manager'   => 'company#make_manager'
  post	'/company/employees/make_non_manager' => 'company#make_non_manager'
  get '/company/employees/edit_email' => 'company#edit_email'
  post '/company/employees/update' => 'company#update_email'
  # get	'/company/teams'		    => 'company#teams'
  # post	'/company/teams/add/complete'	    => 'company#add_teams_complete'
  # get	'/company/teams/edit/:team_id'	    => 'company#edit_teams'
  # post	'/company/teams/edit/:team_id/complete'	    => 'company#edit_teams_complete'
  # post	'/company/teams/delete'		    => 'company#delete_teams'
  # get '/company/team/:id/show'        => 'company#team_show'
  # post	'/company/departments/add/complete'	    => 'company#add_departments_complete'
  # get	'/company/departments/edit' => 'company#edit_departments'
  # post	'/company/departments/edit/complete'	=> 'company#edit_departments_complete'
  # post	'/company/departments/delete'	    => 'company#delete_departments'
  post '/company/confirm_invite_email_setting' => 'company#confirm_invite_email_setting'
 
  # users
  get	'/user'			    => 'users#index'
  get '/user/getname' => 'users#give_recog_by_email'
  post	'/user/give_points'	    => 'users#give_points'
  post	'/user/give_points_slack'   => 'users#give_points_slack'
  #post	'/user/give_comments'	    => 'users#give_comments'
  #post	'/user/give_kudos'	    => 'users#give_kudos'
  post	'/user/give_bonus'	    => 'users#give_bonus'
  post	'/user/delete_post'	    => 'users#delete_post'
  #post	'/user/delete_comment'	    => 'users#delete_comment'

  get	'/profile'		            => 'users#profile'
  get '/profile/given'          => 'users#given'
  get '/profile/timeline'       => 'users#timeline'
  get '/profile/articles'       => 'users#articles'
  post '/profile/give_kudos'    => 'users#give_kudos'
  post '/profile/give_comments' => 'users#give_comments'
  post '/profile/delete_comment' => 'users#delete_comment'

  # get	'/rewards'		    => 'users#rewards'
  # post	'/rewards/request'	    => 'users#rewards_request'
  # get	'/rewards/status'	    => 'users#rewards_status'
  # post	'/rewards/cancel'	    => 'users#rewards_cancel'
  # get	'/bonus'		    => 'users#bonus'
  post '/select_target_department' => 'users#select_target_department'
  post '/select_target_team' => 'users#select_target_team'

  #analytics
  get	'analytics'		=> 'analytics#overall'
  post	'analytics'		=> 'analytics#overall'
  get	'analytics/receiver'	=> 'analytics#index'
  post	'analytics/receiver'	=> 'analytics#index'
  get	'analytics/giver'	=> 'analytics#giver'
  post	'analytics/giver'	=> 'analytics#giver'
  get	'analytics/hashtag'	=> 'analytics#hashtag'
  post	'analytics/hashtag'	=> 'analytics#hashtag'
  get 'analytics/hashtag/points' => 'analytics#hashtagpoints'
  post 'analytics/hashtag/points' => 'analytics#hashtagpoints'
  get	'analytics/hashtag/all' => 'analytics#allhashtag'
  post	'analytics/hashtag/all' => 'analytics#allhashtag'
  get 'analytics/hashtag/all/points' => 'analytics#allhashtagpoints'
  post  'analytics/hashtag/all/points' => 'analytics#allhashtagpoints'
  get 'analytics/users' => 'analytics#users'
  post 'analytics/users' => 'analytics#users'
  get	'analytics/user/:id'	=> 'analytics#user'
  post	'analytics/user/:id'	=> 'analytics#user'
  get 'analytics/user/:id/points'  => 'analytics#userpoints'
  post  'analytics/user/:id/points'  => 'analytics#userpoints'
  get 'analytics/user/:id/given' => 'analytics#usergiven'
  get 'analytics/user/:id/given' => 'analytics#usergiven'
  get 'analytics/user/:id/received' => 'analytics#userreceived'
  get  'analytics/teams'    => 'analytics#teams'
  get 'analytics/pv'  => 'analytics#pv'
  post 'analytics/pv'  => 'analytics#pv'
  #get 'analytics/callback'  => 'analytics#callback'

  post 'tracking/pv' => 'tracking#track_pv'

  # blog
  get '/company/articles' => 'articles#index'
  get '/company/casual_articles' => 'articles#casual'
  get '/company/article/new' => 'articles#new'
  get '/company/article/:id' => 'articles#show'
  post '/company/article/create'  => 'articles#create'
  get '/company/article/:id/edit' => 'articles#edit'
  post '/company/article/:id/update'  => 'articles#update'
  post '/company/article/:id/destory'     => 'articles#destory'
  post '/company/article/:id/publish' => 'articles#publish'
  post '/company/article/send_release_mail' => 'articles#send_release_mail'
  post '/company/article/:id/update_is_new' => 'articles#update_is_new'
  post '/company/article/like' => 'articles#like'
  get '/company/image/:id/edit' => 'articles#image'
  post '/company/image/:id/update' => 'articles#image_update'
  post '/company/image/:id/delete' => 'articles#image_delete'
  get '/company/tags' => 'tags#index'
  get '/company/user_posted_contents' => 'user_posted_contents#index'
  post '/company/user_posted_content/create'  => 'user_posted_contents#create'  

  # banner
  get '/company/banners' => 'banners#index'
  post '/company/banner/create'  => 'banners#create'

  #facebook auth
  get	'auth/facebook', as: "auth_provider"
  get	'auth/facebook/callback',to: "users#fb_auth"

  #forget password
  get	'/forgot_password'		  => 'users#forgot_password'
  post	'/forgot_password/submit'	  => 'users#forgot_password_submit'

  #ios register
  post	'/device/ios/register'		  => 'device#register_ios'
  post	'/device/ios/unregister'	  => 'device#unregister_ios'

  match "*anything" => "top#not_found" , via: [:get, :post , :patch , :delete ]
end

app/models/vote_result.rb
class VoteResult < ActiveRecord::Base
  belongs_to :user
  belongs_to :company
  belongs_to :department
  belongs_to :team
  belongs_to :vote

  scope :of_company, ->(company_id) { where(company_id: company_id) }
  scope :of_department, ->(department_id) { where(department_id: department_id) }
  scope :of_vote, ->(vote_id) { where(vote_id: vote_id) }

  validates :vote_id, uniqueness: { scope: :user_id }
end

app/controllers/admin/vote_results_controller.rb
class Admin::VoteResultsController < Admin::Base
  before_action :set_record, only: :show

  def index
    @votes = Vote.of_company(@user.company_id).finished.where(is_delivered: true).date_order
    @total_employee_count = User.of_company(@user.company_id).available.count
  end

  def show
    @users = User.of_company(@user.company_id).available.index_by(&:id)
    @departments = Department.of_company(@user.company_id).available
    dep_headcount = get_dep_headcount(@departments)
    dep_resultcount = VoteResult.of_company(@user.company_id).of_vote(params[:id]).group(:department_id).count
    @dep_response_rate = get_response_rate(dep_headcount, dep_resultcount)
    @dep_ranking = Hash[ VoteResult.of_company(@user.company_id).of_department(params[:department_id]).of_vote(params[:id]).group(:result).count.sort_by{ |_, v| -v } ]
    @dep_total_vote = VoteResult.of_company(@user.company_id).of_vote(params[:id]).of_department(params[:department_id]).count
  end

  def post_vote
    begin
      if VoteResult.create(vote_result_params)
        redirect_to profile_given_path, notice: "投票しました"
      else
        redirect_to admin_votes_path, notice: "投票に失敗しました"
      end
    rescue => e
      puts "#{e}"
      flash[:notice] = e
      redirect_to profile_given_path
    end
  end

  private
  def get_dep_headcount(departments)
    departments.each_with_object({}) do |dep, hash |
      count = 0
      dep.teams.map { |team| count += team.member_ids.split(",").count }
      hash.store(dep, count )
    end
  end

  def get_response_rate(dep_headcount, dep_resultcount)
    dep_headcount.each_with_object({}) do |(key, value), hash |
      dep_resultcount[key.id].present? ? dep_resultcount[key.id] : dep_resultcount[key.id] = 0
      hash.store(key.dep_name, (dep_resultcount[key.id] / value.to_f).round(3))
    end
  end

  def set_record
    @vote = Vote.find_by(
      id: params[:id],
      company_id: @user.company_id
    )
    unless @vote
      raise ActiveRecord::RecordNotFound, "Vote is not found"
    end
  end

  def vote_result_params
    params.permit(:user_id, :company_id, :team_id, :department_id, :vote_id, :result)
  end
end

app/views/admin/vote_results/index.html.haml
.analytics_holder
  .analytics_time_select
    .clearfix
  = render '/analytics/analytics'
  .analytics_container{ style: "float: left; width: 80%; background-color: white; margin-bottom: 30px;" }
    .analytics_holder.toolbox.width-80-percent#admin_contents{ style: "margin: 0 auto;" }
      %h3.c_align 投票結果一覧
      - if @votes.count > 0
        %table{ style: "margin: 10px auto;", border: 1 }
          %tr.bg-gray
            %th.p-10 配信日
            %th タイトル
            %th 質問内容
            %th 回答数
            %th 回答率
          - @votes.each do |vote|
            %tr
              %td.width-8-percent.c_align.p-10{ style: "word-break: break-all;" }= vote.date
              %td.width-10-percent.c_align{ style: "word-break: break-all;" }= link_to vote.title, admin_vote_result_path(vote.id)
              %td.width-30-percent.c_align{ style: "word-break: break-all;" }= vote.question
              %td.width-10-percent.c_align{ style: "word-break: break-all;" }= vote.vote_results.count
              %td.width-10-percent.c_align{ style: "word-break: break-all;" }= ((vote.vote_results.count / @total_employee_count).round(1) * 100).to_s + "%"
      - else
        .c_align.p-10 投票が開始するまでお待ちください

app/views/admin/vote_results/show.haml.haml
.analytics_holder
  .analytics_time_select
    .clearfix
  = render '/analytics/analytics'
  .analytics_container{ style: "float: left; width: 80%; background-color: white; margin-bottom: 30px;" }
    .analytics_holder.toolbox.width-100-percent#admin_contents
      %h3{ style: "padding-left: 10px; margin: 10px;" } 2018/04/15の投票結果
      %h4{ style: "padding-left: 20px; line-height: 1.8em;"} 質問内容: 今週あなたのチームで最も活躍した人は誰ですか？
      %h4{ style: "padding-left: 20px; line-height: 1.8em;"}  現在の部署ごとの投票率
      #chartContainer{ style: "height: 300px; width: 90%;" }
      %div{ style: "padding-left: 20px; margin: 20px 0;" }
        %select
          %option 対象の部署を選択してください
          %option 人事部
      %table.tbl_tools.width-90-percent{ border: "1" }
        %tr
          %th チーム
          %th 名前
          %th 投票数
          %th 投票率
        %tr
          %td.width-8-percent{ style: "word-break: break-all;" } インフラ
          %td.width-8-percent{ style: "word-break: break-all;" } 山田太郎
          %td.width-8-percent{ style: "word-break: break-all;" } 10
          %td.width-8-percent{ style: "word-break: break-all;" } 60%
        %tr
          %td.width-8-percent{ style: "word-break: break-all;" } 開発
          %td.width-8-percent{ style: "word-break: break-all;" } 山田太郎
          %td.width-8-percent{ style: "word-break: break-all;" } 10
          %td.width-8-percent{ style: "word-break: break-all;" } 25%
        %tr
          %td.width-8-percent{ style: "word-break: break-all;" } 開発
          %td.width-8-percent{ style: "word-break: break-all;" } 佐藤二朗
          %td.width-8-percent{ style: "word-break: break-all;" } 5
          %td.width-8-percent{ style: "word-break: break-all;" } 15%
:javascript
  window.onload = function () {
    var chart = new CanvasJS.Chart("chartContainer", {
      animationEnabled: true,
      theme: "light2", // "light1", "light2", "dark1", "dark2"
      title:{
        text: "部署ごとの投票率"
      },
      axisY: {
        title: "投票率"
      },
      data: [{        
        type: "column",
        dataPoints: [      
          { y: 91.8, label: "メディア事業部" },
          { y: 85.2,  label: "人事部" },
          { y: 79.1,  label: "経営企画部" },
          { y: 63.2,  label: "営業部" },
          { y: 52.4,  label: "新規事業部" },
        ]
      }]
    });
    chart.render();
  }

app/views/admin/vote_results/show.html.erb
<div class="analytics_holder">
  <div class="analytics_time_select">
    <div class="clearfix">
    </div>
  </div>
  <%= render '/analytics/analytics' %>
  <div class="analytics_container" style="float: left; width: 80%; background-color: white; margin-bottom: 30px;">
    <div class="analytics_holder toolbox width-100-percent" id="admin_contents">
      <h3 style="padding-left: 10px; margin: 10px;"><%= @vote.title %></h3>
      <h4 style="padding-left: 20px; line-height: 1.8em;">質問内容: <%= @vote.question %></h4>
      <h4 style="padding-left: 20px; line-height: 1.8em;">現在の部署ごとの投票率</h4>
      <div id="chartContainer" style="padding-left: 20px; margin: 20px 0;height: 300px; width: 80%;"></div>
      <div class="width-90-percent" style="padding-left: 20px; margin: 20px 0;">
        <%=form_tag admin_vote_result_path(@vote.id), method: :get do %>
          <select name="department_id">
            <option value="">詳細を閲覧する部署を選択してください</option>
            <% @departments.each do |dep| %>
              <% if params[:department_id] == dep.id.to_s %>
                <option value=<%= dep.id %> selected><%= dep.dep_name %></option>
              <% else %>
                <option value=<%= dep.id %>><%= dep.dep_name %></option>
              <% end %>
            <% end %>
          <input type="submit"/>
        <% end %>
        <% if @dep_ranking.present? %>
          <table class="tbl_tools width-100-percent" border="1"/>
            <tr>
              <th>名前
              <th>投票数
              <th>投票率
            </tr>
            <% @dep_ranking.each do |key, value| %>
              <tr>
                <td class="width-8-percent" style="word-break: break-all;"><%= "#{@users[key].try(:lastname)} #{@users[key].try(:firstname)}" %></td>
                <td class="width-8-percent" style="word-break: break-all;"><%= value %></td>
                <td class="width-8-percent" style="word-break: break-all;"><%= (value/@dep_total_vote.to_f).round(2) * 100 %>%</td>
              </tr>
            <% end %>
          </table>
        <% else %>
          <p>まだ投票されていません</p>
        <% end %>
        <br/>
        <%= link_to "投票結果一覧へ", admin_vote_results_path %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  window.onload = function () {
    var chart = new CanvasJS.Chart("chartContainer", {
      animationEnabled: true,
      theme: "light2",
      title:{
        text: "部署ごとの投票率"
      },
      axisY: {
        title: "投票率",
        valueFormatString: "##.#%"
      },
      data: [{        
        type: "column",
        color: "#ff8d07",
        yValueFormatString: "##.#%",
        dataPoints: [
          <% @dep_response_rate.each do |key, value| %>
            { y: <%= value %>, label: "<%= key %>" },
          <% end %>
        ]
      }]
    });
    chart.render();
  }
</script>